INSERT INTO "sqlite_sequence" VALUES('photometry',10527);
INSERT INTO "sqlite_sequence" VALUES('sources',2053);
INSERT INTO "sqlite_sequence" VALUES('telescopes',33);
INSERT INTO "sqlite_sequence" VALUES('instruments',47);
INSERT INTO "sqlite_sequence" VALUES('modes',7);
INSERT INTO "sqlite_sequence" VALUES('publications',571);
INSERT INTO "sqlite_sequence" VALUES('spectral_types',2399);
INSERT INTO "sqlite_sequence" VALUES('parallaxes',535);
INSERT INTO "sqlite_sequence" VALUES('systems',15);
